[versions]
# Build tools
agp = "8.13.0"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
jetbrainsKotlinJvm = "2.0.21"
javaxInject = "1"

# AndroidX Core / Lifecycle
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.3"

# Compose / Activity / Navigation
composeBom = "2024.09.00"
activityCompose = "1.11.0"
material3 = "1.3.2"
androidxNavigation = "2.8.5"
androidxHiltNavigationCompose = "1.2.0"

# UI (Views)
appcompat = "1.6.1"
material  = "1.10.0"

# Images
coil = "2.7.0"

# DI / Coroutines / Serialization / biometric
hilt = "2.56"
kotlinxCoroutines = "1.10.1"
kotlinxSerializationJson = "1.8.0"
biometric = "1.1.0"
moshi = "1.15.1"
# Networking / DB / Paging
okhttp   = "4.12.0"
retrofit = "2.11.0"
room     = "2.7.2"
paging   = "3.3.2"
gson = "2.11.0"

# Testing
junit        = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
robolectric  = "4.14.1"
truth        = "1.4.4"
turbine      = "1.2.0"
mockk = "1.13.12"
archCoreTesting = "2.2.0"
androidxTestCore = "1.5.0"
foundation = "1.9.1"
androidx-test = "1.6.1"

[libraries]
# AndroidX Core / Lifecycle
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

# Compose Platform
androidx-compose-bom                = { group = "androidx.compose",      name = "compose-bom",          version.ref = "composeBom" }
androidx-compose-ui                 = { group = "androidx.compose.ui",   name = "ui" }
androidx-compose-ui-graphics        = { group = "androidx.compose.ui",   name = "ui-graphics" }
androidx-compose-material3          = { group = "androidx.compose.material3", name = "material3" ,version.ref = "material3"}
androidx-compose-ui-tooling         = { group = "androidx.compose.ui",   name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui",   name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4     = { group = "androidx.compose.ui",   name = "ui-test-junit4" }
androidx-compose-ui-test-manifest   = { group = "androidx.compose.ui",   name = "ui-test-manifest" }
androidx-activity-compose           = { group = "androidx.activity",     name = "activity-compose",     version.ref = "activityCompose" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# Navigation (Compose + Testing + Hilt)
androidx-navigation-compose  = { group = "androidx.navigation", name = "navigation-compose",  version.ref = "androidxNavigation" }
androidx-hilt-navigation-compose = { group = "androidx.hilt",   name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

# Classic UI (Views)
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material           = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Images (Coil)
coil-kt-compose= { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# DI (Hilt)
hilt-android           = { group = "com.google.dagger", name = "hilt-android",           version.ref = "hilt" }
hilt-compiler          = { group = "com.google.dagger", name = "hilt-compiler",          version.ref = "hilt" }

# Coroutines / Serialization
kotlinx-coroutines-core   = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core",   version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android= { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android",version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test   = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test",   version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json= { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json",version.ref = "kotlinxSerializationJson" }

# Networking
retrofit-core            = { group = "com.squareup.retrofit2", name = "retrofit",                         version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-logging           = { group = "com.squareup.okhttp3",   name = "logging-interceptor",              version.ref = "okhttp" }

# Room (Database)
room-runtime  = { group = "androidx.room", name = "room-runtime",  version.ref = "room" }
room-ktx      = { group = "androidx.room", name = "room-ktx",      version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

# Paging
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
paging-common  = { module = "androidx.paging:paging-common",  version.ref = "paging" }



# biometric
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
# moshi
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# Testing
junit              = { group = "junit",                name = "junit",           version.ref = "junit" }
androidx-junit     = { group = "androidx.test.ext",    name = "junit",           version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
robolectric        = { group = "org.robolectric",      name = "robolectric",     version.ref = "robolectric" }
truth              = { group = "com.google.truth",     name = "truth",           version.ref = "truth" }
turbine            = { group = "app.cash.turbine",     name = "turbine",         version.ref = "turbine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTesting" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }

[plugins]
# Android / Kotlin
android-application = { id = "com.android.application",                 version.ref = "agp" }
android-library     = { id = "com.android.library",                     version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android",            version.ref = "kotlin" }
kotlin-compose      = { id = "org.jetbrains.kotlin.plugin.compose",     version.ref = "kotlin" }
jetbrains-kotlin-jvm= { id = "org.jetbrains.kotlin.jvm",                version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization= { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# DI / Codegen
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp  = { id = "com.google.devtools.ksp",        version.ref = "ksp" }